feat: add privacy level [SD-781]
ydataai/ydata-sdk pull request #34
Opened 2023-03-22 17:41 UTC by ricardodcpereira

This PR adds the privacy level parameter to the public SDK.
I was only able to test the creation of the Synthesizer. The training fails because the DS lib version with the privacy layer is not yet deployed in the dev environment.

![Screenshot from 2023-03-22 17-24-55](https://user-images.githubusercontent.com/21283729/226988634-d8ba3e91-adfa-4373-8e6b-c3f776ae0b91.png)

Here is a usage example:

```python
from ydata.sdk.synthesizers import RegularSynthesizer, PrivacyLevel
from ydata.sdk.datasources import DataSource

X = DataSource.get('{ds-uid}')
synth = RegularSynthesizer()
synth.fit(X, privacy_level=PrivacyLevel.HIGH_PRIVACY)
sample = synth.sample(n_samples=50)
```

2023-03-24 15:09 UTC, ricardodcpereira commented on src/ydata/sdk/synthesizers/_models/privacy.py
> +class PrivacyLevel(Enum):
Done.

2023-03-24 15:25 UTC, aquemy commented on src/ydata/sdk/synthesizers/regular.py
> +            privacy_level (PrivacyLevel): Synthesizer privacy level (defaults to high fidelity)
This should be in the order of the signature.

2023-03-28 09:18 UTC, aquemy approved these changes

2023-03-28 09:53 UTC, aquemy commented
We would need an example of usage (see what has been done for the Anonymizer).

2023-03-28 09:53 UTC, aquemy requested changes
Just noticed that it is missing an example.

2023-03-28 11:08 UTC, ricardodcpereira commented
An example with the privacy level was added.

2023-03-28 14:08 UTC, aquemy approved these changes

2023-03-28 15:33 UTC, merged